<script lang="ts" setup>
import Card from '@/Components/Card.vue';
import Heading from '@/Components/Heading.vue';
</script>

<template>
  <div class="mt-5 flex flex-col gap-5">
    <Card class="mx-auto prose max-w-6xl">
      <Heading :border="false">Privacy Policy</Heading>

      <p class="mb-0">
        Set out below is the Coeliac Sanctuary Privacy Policy, including what
        data we collect, why we need it, how we use it and protect it, and how
        we remove it.
      </p>
    </Card>

    <Card
      id="website"
      class="mx-auto prose max-w-6xl"
    >
      <ol class="space-y-2 text-sm">
        <li class="list-none">
          <span class="text-lg font-semibold"> Coeliac Sanctuary Website </span>
          <ol>
            <li>
              All pages on the Coeliac Sanctuary website use Google Analytics to
              help us understand how our visitors access and find the Coeliac
              Sanctuary website. Google Analytics uses "Cookies", which are tiny
              text files placed on your device so the analytic software can
              watch what pages you visit and how you got there, the analytics
              software only tracks your activity on our own website, and does
              not track you elsewhere.
            </li>
            <li>
              The information generated by the cookie is transmitted securely to
              Google's Servers where they process it in a way so we can access
              it on the Google Analytics website, this information Google store
              may include your IP address, but we do not get access to this
              information, nor do we have any way to data to an actual person.
              For more information please see the
              <a
                title="Google Privacy Policy"
                href="https://policies.google.com/privacy"
                target="_blank"
              >
                Google Analytics Privacy Policy </a
              >.
            </li>
            <li>
              All parts of the Coeliac Sanctuary website are protected by a SSL
              certificate, which means all data is encrypted as it is
              transmitted from your browser to our server.
            </li>
            <li>
              Depending on what parts of the website you use, data we may store
              about you includes, but is not limited to;
              <ol>
                <li>IP Address</li>
                <li>Name</li>
                <li>Email Address</li>
                <li>Postal Address</li>
                <li>Phone Number</li>
              </ol>
            </li>
            <li>
              For full information on why, how, and where we store your data
              please see the below sections of this policy.
            </li>
            <li>
              <span class="text-md font-semibold"> Where to Eat Ratings </span>
              <ol>
                <li>
                  Users have the ability to leave a rating of an eatery through
                  our website.
                </li>
                <li>
                  Users can leave an anonymous star rating without filling out
                  their other details.
                </li>
                <li>
                  If users wish to leave a more detailed rating they need to
                  give their name, email address along with their review.
                </li>
                <li>
                  Your email address is <strong>never</strong> displayed on the
                  website or app, and is only used for validation purposes and
                  spam protection.
                </li>
              </ol>
            </li>
            <li>
              <span class="text-md font-semibold"> Competitions </span>
              <ol>
                <li>
                  During the course of a competition we store all data provided
                  in our database, upon a competition ending all PERSONAL data
                  will be securely removed after one month, we will however keep
                  anonymised data so we can track the number of entrants in a
                  competition, and in special cases where part of our
                  competition is to leave feedback on the website, or suggest
                  new features for the website, these will be kept as long as
                  deemed necessary, but we will remove any personal information
                  from the feedback or suggestions.
                </li>
              </ol>
            </li>
            <li>
              <span class="text-md font-semibold"> Contact Forms </span>
              <ol>
                <li>
                  All data through our contact forms is sent securely to our
                  email address, once the matter has been dealt with the email
                  is permanently deleted.
                </li>
              </ol>
            </li>
            <li>
              <span class="text-md font-semibold"> Newsletter </span>
              <ol>
                <li>
                  All users have the option to sign up to our free newsletter,
                  you can do this through any page on our website, and you can
                  also choose to do it through our competition pages and shop.
                </li>
                <li>
                  The newsletter is strictly opt-in only, and you only need to
                  provide your email, and you can-opt out at any time by
                  pressing the Unsubscribe link at the bottom of each
                  newsletter.
                </li>
              </ol>
            </li>
            <li>
              <span class="text-md font-semibold"> Third Party Policies </span>
              <ol>
                <li>
                  Websites linked from our website are out of our control and we
                  are not responsible for any content, tracking or privacy
                  policies on these websites or services.
                </li>
              </ol>
            </li>
            <li>
              <span class="text-md font-semibold"> Your Rights </span>
              <ol>
                <li>
                  You have the right at any time to request access to all data
                  we store on you, if you wish to do so please put your request
                  in writing to Coeliac Sanctuary, PO Box 643, Crewe, CW1 9LJ
                  and include your Name, Address, Phone Number and Email Address
                  and we will endeavour to provide you with any information we
                  store about you within 1 month on receipt of your request.
                </li>
                <li>
                  You have the right to be forgotten from our website and
                  records, if you wish to do so please put your request in
                  writing to Coeliac Sanctuary, PO Box 643, Crewe, CW1 9LJ and
                  include your Name, Address, Phone Number and Email Address and
                  we will endeavour to delete all personal data we hold about
                  you with the exception of any order invoices, which we legally
                  have to store for 7 (Seven) years.
                </li>
              </ol>
            </li>
          </ol>
        </li>
      </ol>
    </Card>

    <Card
      id="shop"
      class="mx-auto prose max-w-6xl"
    >
      <ol class="space-y-2 text-sm">
        <li class="list-none">
          <span class="text-lg font-semibold"> Coeliac Sanctuary Shop </span>
          <ol>
            <li>
              Personal data is handled in several ways while using our online
              Shop
            </li>
            <li>
              <span class="text-md font-semibold"> Orders </span>
              <ol>
                <li>
                  When you make an order in our online shop your name, email
                  address and postal address are securely stored in our
                  database, we will keep this data securely for at a minimum of
                  seven (7) years for tax purposes. Your information is stored
                  online in password protected environments and offline under
                  lock and key. We do NOT, and never will store any payment
                  information, including, but not limited to, Credit/Debit card
                  numbers, Expiry dates, CVC numbers and PayPal usernames or
                  Passwords.
                </li>
                <li>
                  ALL payment processing is done through external servers
                  (Stripe, Paypal) and your payment details do not get
                  transmitted to our own server.
                </li>
              </ol>
            </li>
            <li>
              <span class="text-md font-semibold"> Baskets </span>
              <ol>
                <li>
                  When you store a temporary cookie on your device with your
                  unique basket identifier, to link the open basket to your
                  device.
                </li>
                <li>
                  This cookie is deleted when you either complete an order, or
                  after one hour of inactivity with our website.
                </li>
              </ol>
            </li>
          </ol>
        </li>
      </ol>
    </Card>

    <Card
      id="app"
      class="mx-auto prose max-w-6xl"
    >
      <ol class="space-y-2 text-sm">
        <li class="list-none">
          <span class="text-lg font-semibold">
            Coeliac Sanctuary - On the Go App
          </span>
          <ol>
            <li>
              <span class="text-md font-semibold"> Your Location </span>
              <ol>
                <li>
                  To show eateries around your location our app will get your
                  current latitude and longitude and securely transmit it to our
                  servers.
                </li>
                <li>
                  We do not get any other data from you when getting your
                  location.
                </li>
                <li>
                  You can still use our app without having to give permission.
                </li>
              </ol>
            </li>
            <li>
              <span class="text-md font-semibold"> Searching for Places </span>
              <ol>
                <li>
                  When you search for a place in our app the text you entered is
                  transmitted to our servers.
                </li>
                <li>
                  We do not get any other data from you when you use the search
                  functionality in our app.
                </li>
              </ol>
            </li>
            <li>
              <span class="text-md font-semibold"> Analytics </span>
              <ol>
                <li>
                  We use Google Firebase Analytics to track anonymous data on
                  how people use our app.
                </li>
                <li>
                  This includes the screens you view, locations opened, and
                  links clicked.
                </li>
                <li>
                  You can opt out of analytical tracking in the app by visiting
                  the 'About' screen in the app, from the main app screen click
                  the 3 lines icon in the top left, then click 'About'.
                </li>
              </ol>
            </li>
            <li>
              <span class="text-md font-semibold"> Advertisements </span>
              <ol>
                <li>
                  We use Google AdMob to display small banners on our app.
                </li>
                <li>
                  This is the only advertisement in our app and is designed to
                  be as unobtrusive as possible.
                </li>
              </ol>
            </li>
            <li>
              <span class="text-md font-semibold"> Where to Eat Ratings </span>
              <ol>
                <li>
                  Users have the ability to leave a rating of an eatery through
                  our app, just like users can on our website.
                </li>
                <li>
                  Users can leave an anonymous star rating without filling out
                  their other details.
                </li>
                <li>
                  If users wish to leave a more detailed rating they need to
                  give their name, email address along with their review.
                </li>
                <li>
                  Your email address is <strong>never</strong> displayed on the
                  website or app, and is only used for validation purposes and
                  spam protection.
                </li>
              </ol>
            </li>
            <li>
              <span class="text-md font-semibold"> Contact Forms </span>
              <ol>
                <li>
                  We have a series of forms through out the app where users can
                  contact us. These include:
                  <ol>
                    <li>Recommend a place</li>
                    <li>Report a place</li>
                  </ol>
                </li>
                <li>
                  These forms may ask for your name and email address along with
                  the place information.
                </li>
                <li>
                  Your email address is <strong>never</strong> displayed on the
                  website or app, and is only used for validation purposes and
                  spam protection.
                </li>
              </ol>
            </li>
          </ol>
        </li>
      </ol>
    </Card>

    <Card class="mx-auto prose max-w-6xl">
      <ol class="list-none space-y-2 text-sm">
        <li>
          <h3>Mediavine Programmatic Advertising (Ver 1.1)</h3>
          <p>
            The Website works with Mediavine to manage third-party
            interest-based advertising appearing on the Website. Mediavine
            serves content and advertisements when you visit the Website, which
            may use first and third-party cookies. A cookie is a small text file
            which is sent to your computer or mobile device (referred to in this
            policy as a “device”) by the web server so that a website can
            remember some information about your browsing activity on the
            Website.
          </p>
          <p>
            First party cookies are created by the website that you are
            visiting. A third-party cookie is frequently used in behavioral
            advertising and analytics and is created by a domain other than the
            website you are visiting. Third-party cookies, tags, pixels, beacons
            and other similar technologies (collectively, “Tags”) may be placed
            on the Website to monitor interaction with advertising content and
            to target and optimize advertising. Each internet browser has
            functionality so that you can block both first and third-party
            cookies and clear your browser’s cache. The "help" feature of the
            menu bar on most browsers will tell you how to stop accepting new
            cookies, how to receive notification of new cookies, how to disable
            existing cookies and how to clear your browser’s cache. For more
            information about cookies and how to disable them, you can consult
            the information at
            <a
              href="https://www.allaboutcookies.org/manage-cookies/"
              target="_blank"
              rel="noreferrer noopener nofollow"
              >All About Cookies</a
            >.
          </p>
          <p>
            Without cookies you may not be able to take full advantage of the
            Website content and features. Please note that rejecting cookies
            does not mean that you will no longer see ads when you visit our
            Site. In the event you opt-out, you will still see non-personalized
            advertisements on the Website.
          </p>
          <p>
            The Website collects the following data using a cookie when serving
            personalized ads:
          </p>
          <ul>
            <li>IP Address</li>
            <li>Operating System type</li>
            <li>Operating System version</li>
            <li>Device Type</li>
            <li>Language of the website</li>
            <li>Web browser type</li>
            <li>Email (in hashed form)</li>
          </ul>
          <p>
            Mediavine Partners (companies listed below with whom Mediavine
            shares data) may also use this data to link to other end user
            information the partner has independently collected to deliver
            targeted advertisements. Mediavine Partners may also separately
            collect data about end users from other sources, such as advertising
            IDs or pixels, and link that data to data collected from Mediavine
            publishers in order to provide interest-based advertising across
            your online experience, including devices, browsers and apps. This
            data includes usage data, cookie information, device information,
            information about interactions between users and advertisements and
            websites, geolocation data, traffic data, and information about a
            visitor’s referral source to a particular website. Mediavine
            Partners may also create unique IDs to create audience segments,
            which are used to provide targeted advertising.
          </p>
          <p>
            If you would like more information about this practice and to know
            your choices to opt-in or opt-out of this data collection, please
            visit
            <a
              href="https://thenai.org/opt-out/"
              target="_blank"
              rel="noreferrer noopener nofollow"
              >National Advertising Initiative opt out page</a
            >. You may also visit
            <a
              href="http://optout.aboutads.info/#/"
              target="_blank"
              rel="noreferrer noopener nofollow"
              >Digital Advertising Alliance website</a
            >
            and
            <a
              href="http://optout.networkadvertising.org/#"
              target="_blank"
              rel="noreferrer noopener nofollow"
              >Network Advertising Initiative website</a
            >
            to learn more information about interest-based advertising. You may
            download the AppChoices app at
            <a
              href="https://youradchoices.com/appchoices"
              target="_blank"
              rel="noreferrer noopener nofollow"
              >Digital Advertising Alliance’s AppChoices app</a
            >
            to opt out in connection with mobile apps, or use the platform
            controls on your mobile device to opt out.
          </p>
          <p>
            For specific information about Mediavine Partners, the data each
            collects and their data collection and privacy policies, please
            visit
            <a
              href="https://www.mediavine.com/ad-partners/"
              target="_blank"
              rel="noreferrer noopener nofollow"
              >Mediavine Partners</a
            >.
          </p>
        </li>
      </ol>
    </Card>
  </div>
</template>
