<?php

declare(strict_types=1);

namespace App\Services\EatingOut\Filters;

use App\Models\EatingOut\Eatery;
use App\Models\EatingOut\EateryCollection;
use App\Models\EatingOut\EateryCounty;
use App\Models\EatingOut\EateryTown;
use App\Models\EatingOut\NationwideBranch;
use App\Services\EatingOut\Collection\Builder\BranchQueryBuilder;
use App\Services\EatingOut\Collection\Builder\EateryQueryBuilder;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Support\Arr;
use Illuminate\Support\Collection;
use Illuminate\Support\Facades\DB;
use RuntimeException;

class GetFiltersForCollection extends GetFiltersForTown
{
    protected ?EateryCollection $collection = null;

    protected ?array $relation = null;

    protected string $column = '';

    protected string $value = '';

    public function handle(array $filters = []): array
    {
        return [
            ...parent::handle($filters),
            'towns' => $this->getTowns()->values(),
            'counties' => $this->getCounties()->values(),
        ];
    }

    /** @return Collection<int, non-empty-array> */
    protected function getTowns(): Collection
    {
        return $this->resolveFilters(EateryTown::class, 'towns', 'town', 'town', 'id', fn (EateryTown $filter) => [
            'label' => "{$filter->town}, {$filter->county->county}" . ($filter->hasAttribute('eateries_count') ? " - ({$filter->eateries_count})" : ''),
        ]);
    }

    /** @return Collection<int, non-empty-array> */
    protected function getCounties(): Collection
    {
        return $this->resolveFilters(EateryCounty::class, 'counties', 'county', 'county', 'id', fn (EateryCounty $filter) => [
            'label' => "{$filter->county}, {$filter->country->country}" . ($filter->hasAttribute('eateries_count') ? " - ({$filter->eateries_count})" : ''),
        ]);
    }

    protected function getColumnForFilterable(string $filterable): string
    {
        if ($filterable === EateryTown::class) {
            return 'wheretoeat_towns.id';
        }

        if($filterable === EateryCounty::class) {
            return 'wheretoeat_counties.id';
        }

        return parent::getColumnForFilterable($filterable); // TODO: Change the autogenerated stub
    }

    protected function getValueForFilterable(string $filterable): string
    {
        if ($filterable === EateryTown::class) {
            return 'wheretoeat.town_id';
        }

        if($filterable === EateryCounty::class) {
            return 'wheretoeat.county_id';
        }

        return parent::getValueForFilterable($filterable); // TODO: Change the autogenerated stub
    }

    public function setCollection(EateryCollection $collection): self
    {
        $this->collection = $collection;

        return $this;
    }

    protected function withWhereClause(Builder $builder): Builder
    {
        if ( ! $this->collection) {
            throw new RuntimeException('Collection not set');
        }

        return $builder
            ->select('*')
            ->when($builder->getModel() instanceof EateryTown, fn (Builder $builder) => $builder->with(['county']))
            ->when($builder->getModel() instanceof EateryCounty, fn (Builder $builder) => $builder->with(['country']))
            ->selectRaw("({$this->eateryQuery()}) + ({$this->branchQuery()}) as eateries_count");
    }

    protected function getIds(): array
    {
        return once(function () {
            $eateries = DB::select(new EateryQueryBuilder($this->collection->configuration)->toSql());
            $branches = DB::select(new BranchQueryBuilder($this->collection->configuration)->toSql());

            return [
                'eateryIds' => Arr::pluck($eateries, 'id'),
                'branchIds' => Arr::pluck($branches, 'branch_id'),
            ];
        });
    }

    protected function eateryQuery(): string
    {
        return Eatery::query()
            ->selectRaw('count(*)')
            ->whereIn('id', Arr::get($this->getIds(), 'eateryIds', []))
            ->where('live', true)
            ->when(
                $this->relation,
                fn (Builder $builder) => $builder->leftJoin(...$this->relation)->whereColumn($this->column, $this->value), /** @phpstan-ignore-line */
                fn (Builder $builder) => $builder->whereColumn($this->column, $this->value)
            )
            ->toRawSql();
    }

    protected function branchQuery(): string
    {
        return NationwideBranch::query()
            ->selectRaw('count(*)')
            ->whereIn('id', Arr::get($this->getIds(), 'branchIds', []))
            ->where('live', true)
            ->whereHas('eatery', fn (Builder $query) => $query
                ->when(
                    $this->relation,
                    fn (Builder $builder) => $builder->leftJoin(...$this->relation)->whereColumn($this->column, $this->value), /** @phpstan-ignore-line */
                    fn (Builder $builder) => $builder->whereColumn($this->column, $this->value)
                ))
            ->toRawSql();
    }

    protected function orderBy(Builder $builder, string $field): Builder
    {
        return $builder->orderBy($field);
    }
}
